### ISSUE TITLE
Feat. req.: Add a way to find top games in a tag that's not in the top 500

### ISSUE THREAD

**Issue by Freso** [250/Steam-Top-250#14]
E.g., if I want to see the top [Base Building](http://store.steampowered.com/tags/en/Base+Building) games, it's not currently possible to do this through the site interface. (I tried hacking the URL – http://steam250.com/tag/base_building – but no cigar.)

I looked through the code to see how the list of tags was gotten, and it seems like it's dynamically generated based on the most used ones, so it's not just a question of adding tags to it manually.

**Comment by Bilge** [comment]
A tag must be applied to at least [500](https://github.com/250/Steam-Top-250/blob/cfa9243a676ee549f19a88583b3e494714369df9/src/Database/Queries.php#L92) games to be considered noteworthy for inclusion. Adding more tags slows down the build. *Base Building* is currently applied to 174 games so it is nowhere near the threshold.
