### ISSUE TITLE
Feat. req.: Enable combining criteria

### ISSUE THREAD

**Issue by Freso** [250/Steam-Top-250#15]
There's currently no way to find top Free games for Linux with the "Story Rich" tag. Or a way to find top games that have both "Adventure" and "Open World" tags. Or 2017 games that are currently discounted. Etc.

It would be great to have a way to combine multiple criteria to get a more specific list.

**Comment by Bilge** [comment]
As you may note from the list of [upcoming features](https://www.patreon.com/steam250) listed on Patreon, this is planned for the new version of the site, but will take many months before it's ready.
