### ISSUE TITLE
Make site look good on mobile

### ISSUE THREAD

**Issue by Bilge** [250/Steam-Top-250#7]
The current state of the site's appearance is result of the classic fallacy of letting the developer touch the CSS. Very open to ideas for improving the layout, especially on mobile.

**Comment by MManifesto** [comment]
Hey - saw your reply on reddit and whipped this up in a few minutes: https://codepen.io/abissonnette/pen/wPOZmg?editors=1100

Drop that css into your site and add the "table-responsive" class to your table and your site should be mobile friendly.

Definitely more could be done but this is a pretty quicky + dirty fix to improve the mobile experience.

**Comment by Bilge** [comment]
@MManifesto That's a very interesting idea: to transform the list into a vertical table. I wanted to explore the possibility of keeping it horizontal, though, but just scaling everything down. But if that doesn't work we can go with your idea. 👍 

In any case, it won't be mobile-friendly without the `<meta name="viewport" content="width=device-width, initial-scale=1">` tag. I think any such mobile improvements need to be built around that scaling.

**Comment by MManifesto** [comment]
Oh, here is a scaled version then :) https://codepen.io/abissonnette/pen/POgxNB?editors=1100

I much prefer the stacked tables.

**Comment by Bilge** [comment]
I definitely prefer unstacked. However, we can lose the size fade on mobile to make proper use of the space. Whilst CodePen can be useful to convey an idea, it's not very useful if it doesn't support the meta viewport tag, because we can't see what it *really* looks like on mobile with native scaling applied.

If you need help setting up the project locally let me know. You should just need to check out this repository and download one of the more [recent database snapshots](https://github.com/250/Steam-data/raw/master/201712/06/123/steam.sqlite). With a copy of PHP 7.1 and Composer installed, run `composer install` and then `bin/generate site steam.sqlite` or `bin/generate page 250 steam.sqlite` if you just want one page.

**Comment by Bilge** [comment]
Fixed via 7146dcad77f16c32cd4904a49200bb9040adc0f0..a1045f5a25dfdef3caed2324f3f966bc57493ec8 [[compare](https://github.com/250/Steam-Top-250/compare/7146dcad77f16c32cd4904a49200bb9040adc0f0...a1045f5a25dfdef3caed2324f3f966bc57493ec8)].
