### ISSUE TITLE
Hidden Gems negative vote bias is too high

### ISSUE THREAD

**Issue by Bilge** [250/Steam-Top-250#9]
Consider two games, both with 100% approval rating. The first has 235 votes, the second has 181 votes. The first has 28K players, the second has 6K players. How should they be ranked against each other?

![screenshot-2017-12-17 hidden gems of steam](https://user-images.githubusercontent.com/470626/34082352-62d4a32c-e354-11e7-95e4-2f354b161c54.png)

It may surprise you to learn that not only is the second game (Blue Revolver) ranked above the first (Mindshow), but they're *three places* apart! So why is that? To find out we have to pluck a few more numbers. Knowing that *100%* is a rounded figure, we can start by looking into the raw scores.

| | Blue Revolver | Mindshow |
|---|---|---|
| Positive | 181 | 234 |
| Negative | 0 | 1 |

That singular, negative review carries so much weight that it drags the game down three ranks, despite having more reviews overall and almost 5x more players.

@woctezuma I think we need to adjust the weighting to address this.

---
📓 Note: this data was generated from [dump #134](https://github.com/250/Steam-data/blob/master/201712/15/134/steam.sqlite).

**Comment by woctezuma** [comment]
I think it is the intended behavior, because the ranking for hidden gems try to favor games of high quality (which is the case for both examples, as shown by the reviews) yet surprisingly little number of players (in this regard, Blue Revolver is more hidden with 4-5 times fewer players).

**Comment by Bilge** [comment]
Are you saying number of players actually sinks games rather than raises them?

**Comment by woctezuma** [comment]
Yes, there is a trade-off between:

- Wilson score (review score taking into account the number of reviews),
- and number of players (as estimated by SteamSpy).

That being said, to avoid giving too much influence to that one negative review for _Mindshow_, one could decrease the weight for the Wilson score (currently `$wilson_weight = 1.96`), which is akin to decreasing _confidence_ value (see [table](https://en.wikipedia.org/wiki/Normal_distribution#Quantile_function) on Wikipedia).

**Comment by Bilge** [comment]
It seems either increasing *or* decreasing the confidence interval just moves them further apart. Decreasing it actually places Blue Revolver at #1. Anyway, it seems you're still happy with the list after bringing this to your attention, so there's no need to make a change. As far as I'm concerned this is still your list so if you're happy, I'm happy; I just wanted to bring it to your attention. 👍
